import { Schema, model, models } from "mongoose";

const listingSchema = new Schema(
  {
    userId: { type: Schema.Types.ObjectId, ref: "User", required: true, index: true },
    street: { type: String, required: true, trim: true },
    unit: { type: String, trim: true },
    city: { type: String, required: true, trim: true },
    state: { type: String, required: true, trim: true },
    zip: { type: String, required: true, trim: true },
    county: { type: String, trim: true },
    legalLot: { type: String, trim: true },
    legalBlock: { type: String, trim: true },
    legalAddition: { type: String, trim: true },
    /** Full legal description from tax/appraiser records (single field like competitor flows). */
    legalDescription: { type: String, trim: true, default: "" },
    propertyType: {
      type: String,
      enum: ["SINGLE_FAMILY", "CONDOMINIUM"],
      default: "SINGLE_FAMILY",
    },
    parcelId: { type: String, trim: true },
    sellerNames: { type: String, trim: true },
    contactPhone: { type: String, trim: true },
    contactEmail: { type: String, trim: true, lowercase: true },
    feeSimpleConfirmed: { type: Boolean, default: false },
    tenantOccupied: { type: Boolean, default: false },
    namedSubdivision: { type: Boolean, default: false },
    subdivisionName: { type: String, trim: true },
    associationType: {
      type: String,
      enum: ["HOA", "CONDO", "NONE"],
      default: "NONE",
    },
    newConstruction: { type: Boolean, default: false },
    septicSystem: { type: Boolean, default: false },
    hasSolarSystem: { type: Boolean, default: false },
    hasPool: { type: Boolean, default: false },
    lockboxOrKeypad: { type: Boolean, default: false },
    lockboxInstructions: { type: String, trim: true, default: "" },
    ownershipType: {
      type: String,
      enum: ["INDIVIDUAL", "MARRIED_COUPLE", "DECEASED_ESTATE", "BUSINESS_ENTITY", "POWER_OF_ATTORNEY"],
      default: "INDIVIDUAL",
    },
    allSignersUsCitizens: { type: Boolean, default: true },
    anyOwnerLicensedAgent: { type: Boolean, default: false },
    allOwnersOccupyProperty: { type: Boolean, default: true },
    businessEntityName: { type: String, trim: true },
    businessEntityRegisteredName: { type: String, trim: true },
    businessEntitySignerName: { type: String, trim: true },
    businessEntitySignerTitle: { type: String, trim: true },
    businessEntitySignerEmail: { type: String, trim: true, lowercase: true },
    allOwnersConsentEsign: { type: Boolean, default: false },
    appointmentPhone: { type: String, trim: true },
    appointmentPhoneCanText: { type: Boolean, default: false },
    alternatePhone: { type: String, trim: true },
    alternatePhoneCanText: { type: Boolean, default: false },
    appointmentEmail: { type: String, trim: true, lowercase: true },
    listingStartOn: { type: Date, default: null },
    listingEndOn: { type: Date, default: null },
    flatFee: { type: Number, default: null },
    protectionPeriodDays: { type: Number, default: null },
    intermediaryStatusAuthorized: { type: Boolean, default: false },
    buyerAgentCompType: {
      type: String,
      enum: ["PERCENT", "AMOUNT"],
      default: "PERCENT",
    },
    buyerAgentCompAmount: { type: Number, default: null },
    exclusions: { type: String, default: "" },
    hoaRequired: { type: Boolean, default: false },
    improvementsAndAccessories: { type: String, default: "" },
    publicRemarks: { type: String, default: "" },
    privateRemarks: { type: String, default: "" },
    drivingDirections: { type: String, default: "" },
    crossStreet: { type: String, trim: true },
    schedulingService: { type: String, trim: true },
    keyboxPermission: { type: Boolean, default: false },
    keyboxRiskAcknowledged: { type: Boolean, default: false },
    firstPhotoExteriorConfirmed: { type: Boolean, default: false },
    photoNoSignsConfirmed: { type: Boolean, default: false },
    photoNoPeoplePetsConfirmed: { type: Boolean, default: false },
    photoCopyrightConfirmed: { type: Boolean, default: false },
    yearBuilt: { type: Number, default: null },
    isInMudWaterDistrict: { type: Boolean, default: false },
    fairHousingNoticeConfirmed: { type: Boolean, default: false },
    valuablesNoticeConfirmed: { type: Boolean, default: false },
    securitySurveillanceAcknowledged: { type: Boolean, default: false },
    iabsAcknowledged: { type: Boolean, default: false },
    sellersDisclosureAcknowledged: { type: Boolean, default: false },
    listingAgreementAcknowledged: { type: Boolean, default: false },
    brokerBrandingConfirmed: { type: Boolean, default: false },
    informationAccurateConfirmed: { type: Boolean, default: false },
    referredByExistingCustomer: { type: Boolean, default: false },
    wantsListingProcessFeedback: { type: Boolean, default: false },
    mlsName: { type: String, trim: true },
    mlsNumber: { type: String, trim: true },
    listingId: { type: String, trim: true },
    /** Where the seller wants the property marketed (replaces requiring MLS numbers at intake). */
    listingPlatforms: { type: [String], default: [] },
    /** Optional gallery URLs (upload or paste); not required to finalize. */
    additionalPhotoUrls: { type: [String], default: [] },
    status: {
      type: String,
      enum: ["INCOMPLETE", "ACTIVE", "PENDING", "EXPIRED", "SOLD"],
      default: "INCOMPLETE",
    },
    planLabel: { type: String, trim: true },
    price: { type: Number, required: true },
    buyerAgentCompPct: { type: Number, default: null },
    description: { type: String, default: "" },
    heroImageUrl: { type: String, trim: true },
    /** Set only for checkout-linked listings; omit (do not null) so sparse unique index allows many intake-created listings */
    sourceOrderId: { type: String, trim: true, sparse: true, unique: true },
    orderedOn: { type: Date, default: null },
    listedOn: { type: Date, default: null },
    expiresOn: { type: Date, default: null },
    setupFinalizedAt: { type: Date, default: null },
    /** True when status is PENDING solely because listingStartOn is in the future. */
    scheduledActivationPending: { type: Boolean, default: false },
  },
  { timestamps: true },
);

export const Listing = models.Listing ?? model("Listing", listingSchema);
